

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x91042480,
     0x1d04e0e0,
     0x81042480,
     0x240100e0,
     0x240002c1,
     0x24402881,
     0xe1002180,
     0x240010c0,
     0x24000080,
     0x240002c1,
     0x24402c81,
     0xe1002180,
     0x9100bf80,
     0x8100bc80,
     0x2400241f,
     0x2a000000 };

