

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x91042480,
     0x1d04e0e0,
     0x81042480,
     0x240120e0,
     0x240002c1,
     0x24202881,
     0xe1002180,
     0x240010c0,
     0x24000080,
     0x240002c1,
     0x24202c81,
     0xe1002180,
     0x240001c7,
     0x24000487,
     0x240fffe8,
     0x240064e9,
     0x9100bf80,
     0x240005ea,
     0xd110ff00,
     0xc910ff00,
     0x0501eaea,
     0x6f00eafd,
     0x240001f0,
     0xd110ff00,
     0xc910ff00,
     0x10ffffe4,
     0x10ffffe4,
     0x10ffffe4,
     0x0101f0f0,
     0xe1000790,
     0x0104e7e7,
     0x0501e9e9,
     0x6f00e9f7,
     0x240001e1,
     0x81003c81,
     0x2400241f,
     0x2a000000 };

